/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import network.request.ROMPResponse;

/**
 *
 * @author jona1993
 */
public class ClientGUI extends javax.swing.JDialog {
    private Socket soc;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private String Login = "dummy";
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        
    }
    
    public ClientGUI(Socket s, ObjectInputStream oi, ObjectOutputStream oo, String login) {
        initComponents();
        
        PanelJour1.setVisible(false);
        ois = oi;
        oos = oo;
        Login = login;
        
        try {
            RefreshRoomsAvalibles();
            RefreshReservations();
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void RefreshRoomsAvalibles() throws IOException, ClassNotFoundException{
        ROMPResponse rep;
        
        rep = new ROMPResponse(ROMPResponse.OK, "-", "GetFreeRooms");
        oos.writeObject(rep);

        DefaultComboBoxModel model = new DefaultComboBoxModel<String>();

        model.addElement("Sélection");

        rep = (ROMPResponse)ois.readObject();

        if(rep.getCode() == ROMPResponse.OK)
        {
            for(int i = 0; i < rep.getChargeUtile().split("#").length; i+=1)
                model.addElement(rep.getChargeUtile().split("#")[i]);
                //ActivitesCB.addItem(rep.getChargeUtile().split("#")[i]);
        }
        ActivitesCB.setModel(model);
        ActivitesCB.setSelectedIndex(0);
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ActivitesCB = new javax.swing.JComboBox<>();
        PanelJour1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DateDebutTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginTF = new javax.swing.JTextField();
        ReserverButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DateFinTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ActivitesTA = new javax.swing.JScrollPane();
        ActivitesTextArea = new javax.swing.JTextArea();
        CancelReservationLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RemoveReservationTF = new javax.swing.JTextField();
        CancelReservationButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LoginModifyTF = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CarteTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Logements disponnibles: ");

        ActivitesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélection" }));
        ActivitesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivitesCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Date Début:");

        jLabel3.setText("Login: ");
        jLabel3.setToolTipText("");

        ReserverButton.setText("Réserver");
        ReserverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserverButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Date Fin:");

        javax.swing.GroupLayout PanelJour1Layout = new javax.swing.GroupLayout(PanelJour1);
        PanelJour1.setLayout(PanelJour1Layout);
        PanelJour1Layout.setHorizontalGroup(
            PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJour1Layout.createSequentialGroup()
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJour1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(ReserverButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelJour1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginTF)
                            .addComponent(DateDebutTF, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(DateFinTF))))
                .addContainerGap())
        );
        PanelJour1Layout.setVerticalGroup(
            PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJour1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DateDebutTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateFinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelJour1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReserverButton)
                .addGap(22, 22, 22))
        );

        jLabel4.setText("Logements réservés: ");

        ActivitesTextArea.setColumns(20);
        ActivitesTextArea.setRows(5);
        ActivitesTA.setViewportView(ActivitesTextArea);

        CancelReservationLabel.setText("Annuler réservation:");

        jLabel5.setText("ID de la réservation: ");

        CancelReservationButton.setText("Annuler");
        CancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Login: ");

        SubmitButton.setLabel("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Payer: ");

        jLabel9.setText("N°Carte: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(PanelJour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActivitesCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(LoginModifyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ActivitesTA, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(CancelReservationLabel))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelReservationButton)
                            .addComponent(SubmitButton)
                            .addComponent(CarteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveReservationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ActivitesTA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(LoginModifyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveReservationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelReservationLabel)
                            .addComponent(CancelReservationButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CarteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ActivitesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(PanelJour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ActivitesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivitesCBActionPerformed
        // TODO add your handling code here:
        if(ActivitesCB.getSelectedItem().toString().compareTo("Sélection") != 0)
        {
            PanelJour1.setVisible(true);
            Date d = new Date();
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            Calendar c = Calendar.getInstance();
            c.setTime(d);
            
            DateDebutTF.setText(f.format(d));
            c.add(Calendar.DATE, 1);
            DateFinTF.setText(f.format(c.getTime()));
            
        }
        else
        {
            PanelJour1.setVisible(false);
        }
    }//GEN-LAST:event_ActivitesCBActionPerformed

    private void ReserverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserverButtonActionPerformed
        // TODO add your handling code here:
        
        ROMPResponse rep;
        String sender = "";
        
        
        try
        {
            sender += LoginTF.getText() + "#" + ActivitesCB.getSelectedItem().toString().split("/ ")[0].split("°")[1] + "#" + DateDebutTF.getText() + "#" + DateFinTF.getText();
            System.err.println(sender);
            rep = new ROMPResponse(ROMPResponse.OK, sender, "BROOM");
            
            oos.writeObject(rep);
            
            rep = (ROMPResponse)ois.readObject();
            
            RefreshRoomsAvalibles();
            RefreshReservations();
            
            if(rep.getCode() == ROMPResponse.OK)
                JOptionPane.showMessageDialog(null, "Réservé avec succès", "Success", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Une erreur est survenue..", "Error", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(NumberFormatException | ClassNotFoundException | IOException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_ReserverButtonActionPerformed

    private void CancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReservationButtonActionPerformed
        // TODO add your handling code here:
        if(RemoveReservationTF.getText().length() > 0){
            ROMPResponse rep;
            String sender = "";

            try
            {

                sender = LoginModifyTF.getText() + "#" + RemoveReservationTF.getText();
                
                rep = new ROMPResponse(ROMPResponse.OK, sender, "CROOM");

                oos.writeObject(rep);

                rep = (ROMPResponse)ois.readObject();

                RefreshReservations();

                if(rep.getCode() == ROMPResponse.OK)
                    JOptionPane.showMessageDialog(null, "Supprimé avec succès", "Success", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "L'id n'existe pas", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException | ClassNotFoundException | IOException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_CancelReservationButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        
        if(CarteTF.getText().length() > 0){
            ROMPResponse rep;
            String sender = "";

            try
            {

                sender = LoginModifyTF.getText() + "#" + RemoveReservationTF.getText() + "#" + CarteTF.getText();
                
                rep = new ROMPResponse(ROMPResponse.OK, sender, "PROOM");

                oos.writeObject(rep);

                rep = (ROMPResponse)ois.readObject();

                RefreshReservations();

                if(rep.getCode() == ROMPResponse.OK)
                    JOptionPane.showMessageDialog(null, "Payé avec succès", "Success", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "L'id n'existe pas", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException | ClassNotFoundException | IOException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void RefreshReservations() throws IOException, ClassNotFoundException
    {
        ROMPResponse rep = new ROMPResponse(ROMPResponse.OK, null, "LROOMS");
        
        oos.writeObject(rep);
        oos.flush();
        
        rep = (ROMPResponse)ois.readObject();
        
        ActivitesTextArea.setText("");
        
        if(rep.getCode() == ROMPResponse.OK)
            for(int i = 0; i < rep.getChargeUtile().split("#").length; i+=1){
                ActivitesTextArea.append(rep.getChargeUtile().split("#")[i] + "\n");
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ActivitesCB;
    private javax.swing.JScrollPane ActivitesTA;
    private javax.swing.JTextArea ActivitesTextArea;
    private javax.swing.JButton CancelReservationButton;
    private javax.swing.JLabel CancelReservationLabel;
    private javax.swing.JTextField CarteTF;
    private javax.swing.JTextField DateDebutTF;
    private javax.swing.JTextField DateFinTF;
    private javax.swing.JTextField LoginModifyTF;
    private javax.swing.JTextField LoginTF;
    private javax.swing.JPanel PanelJour1;
    private javax.swing.JTextField RemoveReservationTF;
    private javax.swing.JButton ReserverButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
