/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import network.request.FUCAMPResponse;

/**
 *
 * @author jona1993
 */
public class ClientGUI extends javax.swing.JDialog {
    private Socket soc;
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private String Login = "dummy";
    
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        
    }
    
    public ClientGUI(Socket s, ObjectInputStream oi, ObjectOutputStream oo, String login) {
        initComponents();
        
        PanelJour1.setVisible(false);
        ois = oi;
        oos = oo;
        Login = login;
        
        FUCAMPResponse rep;
        
        try 
        {
            rep = new FUCAMPResponse(FUCAMPResponse.OK, "-", "GetActivitiesDay");
            oos.writeObject(rep);
            
            rep = (FUCAMPResponse)ois.readObject();
            if(rep.getCode() == FUCAMPResponse.OK)
            {
                ActivitesCB.addItem("<<  Activités 1 jour  >>");
                
                for(int i = 0; i < rep.getChargeUtile().split("#").length; i+=1)
                    ActivitesCB.addItem(rep.getChargeUtile().split("#")[i]);
            }
            
            rep = new FUCAMPResponse(FUCAMPResponse.OK, "+", "GetActivitiesDay");
            oos.writeObject(rep);
            
            rep = (FUCAMPResponse)ois.readObject();
            if(rep.getCode() == FUCAMPResponse.OK)
            {
                ActivitesCB.addItem("<< Activités +1 jour >>");
                for(int i = 0; i < rep.getChargeUtile().split("#").length; i+=1)
                    ActivitesCB.addItem(rep.getChargeUtile().split("#")[i]);
            }
            
            RefreshActivities();
            
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ActivitesCB = new javax.swing.JComboBox<>();
        PanelJour1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DateTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NomTF = new javax.swing.JTextField();
        ReserverButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ActivitesTA = new javax.swing.JScrollPane();
        ActivitesTextArea = new javax.swing.JTextArea();
        CancelReservationLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RemoveReservationTF = new javax.swing.JTextField();
        CancelReservationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Activités Disponnibles:");

        ActivitesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélection" }));
        ActivitesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivitesCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Date Souhaitée:");

        jLabel3.setText("Nom: ");

        ReserverButton.setText("Réserver");
        ReserverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelJour1Layout = new javax.swing.GroupLayout(PanelJour1);
        PanelJour1.setLayout(PanelJour1Layout);
        PanelJour1Layout.setHorizontalGroup(
            PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJour1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateTF)
                    .addComponent(NomTF))
                .addContainerGap())
            .addGroup(PanelJour1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ReserverButton)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        PanelJour1Layout.setVerticalGroup(
            PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJour1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelJour1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReserverButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Activités réservés: ");

        ActivitesTextArea.setColumns(20);
        ActivitesTextArea.setRows(5);
        ActivitesTA.setViewportView(ActivitesTextArea);

        CancelReservationLabel.setText("Annuler réservation:");

        jLabel5.setText("ID de la réservation: ");

        CancelReservationButton.setText("Annuler");
        CancelReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReservationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(PanelJour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActivitesCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancelReservationLabel)
                            .addComponent(ActivitesTA, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveReservationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(CancelReservationButton)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ActivitesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelJour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ActivitesTA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelReservationLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RemoveReservationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelReservationButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ActivitesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivitesCBActionPerformed
        // TODO add your handling code here:
        if(ActivitesCB.getSelectedItem().toString().compareTo("Sélection") != 0 && 
                !ActivitesCB.getSelectedItem().toString().contains("<"))
        {
            PanelJour1.setVisible(true);
            Date d = new Date();
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            DateTF.setText(f.format(d));
            
        }
        else
        {
            PanelJour1.setVisible(false);
        }
    }//GEN-LAST:event_ActivitesCBActionPerformed

    private void ReserverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserverButtonActionPerformed
        // TODO add your handling code here:
        
        FUCAMPResponse rep;
        String sender = "";
        String datedebutBrut;
        datedebutBrut = ActivitesCB.getSelectedItem().toString().split("/ ")[1].split(" jour")[0].trim(); // ->/ [x] jour <-
        
        
        try
        {
            SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
            Date datefin = f.parse(DateTF.getText());
            Calendar c = Calendar.getInstance();
            c.setTime(datefin);
            c.add(Calendar.DATE, Integer.parseInt(datedebutBrut));
            datedebutBrut = f.format(c.getTime());

            sender += Login + "#" + ActivitesCB.getSelectedItem().toString().split("/")[0].trim() + "#" + DateTF.getText() + "#" + datedebutBrut;
            System.err.println(sender);
            rep = new FUCAMPResponse(FUCAMPResponse.OK, sender, "RESERVER");
            
            oos.writeObject(rep);
            
            rep = (FUCAMPResponse)ois.readObject();
            
            RefreshActivities();
            
            if(rep.getCode() == FUCAMPResponse.OK)
                JOptionPane.showMessageDialog(null, "Réservé avec succès", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(NumberFormatException | ParseException | ClassNotFoundException | IOException e)
        {
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_ReserverButtonActionPerformed

    private void CancelReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReservationButtonActionPerformed
        // TODO add your handling code here:
        if(RemoveReservationTF.getText().length() > 0){
            FUCAMPResponse rep;
            String sender = "";

            try
            {

                sender = Login + "#" + RemoveReservationTF.getText();
                System.err.println(sender);
                rep = new FUCAMPResponse(FUCAMPResponse.OK, sender, "CancelReservation");

                oos.writeObject(rep);

                rep = (FUCAMPResponse)ois.readObject();

                RefreshActivities();

                if(rep.getCode() == FUCAMPResponse.OK)
                    JOptionPane.showMessageDialog(null, "Supprimé avec succès", "Success", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "L'id n'existe pas", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(NumberFormatException | ClassNotFoundException | IOException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_CancelReservationButtonActionPerformed

    private void RefreshActivities() throws IOException, ClassNotFoundException
    {
        FUCAMPResponse rep = new FUCAMPResponse(FUCAMPResponse.OK, Login, "GetReservationsActivites");
        
        oos.writeObject(rep);
        oos.flush();
        
        rep = (FUCAMPResponse)ois.readObject();
        
        ActivitesTextArea.setText("");
        
        if(rep.getCode() == FUCAMPResponse.OK)
            for(int i = 0; i < rep.getChargeUtile().split("#").length; i+=1){
                ActivitesTextArea.append(rep.getChargeUtile().split("#")[i] + "\n");
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ActivitesCB;
    private javax.swing.JScrollPane ActivitesTA;
    private javax.swing.JTextArea ActivitesTextArea;
    private javax.swing.JButton CancelReservationButton;
    private javax.swing.JLabel CancelReservationLabel;
    private javax.swing.JTextField DateTF;
    private javax.swing.JTextField NomTF;
    private javax.swing.JPanel PanelJour1;
    private javax.swing.JTextField RemoveReservationTF;
    private javax.swing.JButton ReserverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
