/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.Socket;
import java.net.SocketAddress;
import java.net.UnknownHostException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import network.chatudp.Receiver;
import network.poolthreadserver.ConsoleServeur;
import network.security.digest.BCDigest;

/**
 *
 * @author jona1993
 */
public class ChatGUI extends javax.swing.JDialog implements ConsoleServeur {
    private String chatAddress = null;
    private int PortChat = 0;
    private String Login = "Dummy";
    private String idReservation = null;
    private MulticastSocket soc;
    private InetAddress addrGroupe;
    private String IPLocal;
    /**
     * Creates new form ChatGUI
     */
    public ChatGUI() {
        initComponents();
    }
    
    public ChatGUI(String login, String chataddr, String Port, String idReserv, String LocalIp) {
        initComponents();
        
        chatAddress = chataddr;
        PortChat = Integer.parseInt(Port);
        Login = login;
        idReservation = idReserv;
        IPLocal = LocalIp;
        
        try
        {
            addrGroupe = InetAddress.getByName(chatAddress);
            soc = new MulticastSocket(PortChat);
            soc.joinGroup(addrGroupe);
            soc.setInterface(InetAddress.getByName(LocalIp));
        } catch (UnknownHostException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Receiver recv = new Receiver(soc, this);
        recv.start();
        
        
        ConversTA.append("Server > Bienvenue sur le chat: " + chatAddress + ":" + PortChat + "\n");
        ConversTA.append("Server > Votre username est " + login + ".\n");
        if(idReservation != null)
            ConversTA.append("Server > Votre numéro de réservation est " + idReserv + ".\n");
        else
            ConversTA.append("Server > Bonjour cher(e) employé(e)!\n");
        
        GetHelp();
        
        byte[] msg = ("POST_EVENT#" + Login + "#" + "Connected !\n").getBytes();
        
        
        DatagramPacket dp = new DatagramPacket(msg, msg.length, addrGroupe, PortChat);
        try {
            soc.send(dp);
        } catch (IOException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SaisieTF = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConversTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Saisie: ");

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        ConversTA.setEditable(false);
        ConversTA.setColumns(20);
        ConversTA.setRows(5);
        jScrollPane1.setViewportView(ConversTA);

        jLabel2.setText("Conversation: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SaisieTF, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(SendButton))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SaisieTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        // TODO add your handling code here:
        byte[] msg;
        Scanner scan = new Scanner(SaisieTF.getText());
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        try
        {
            if(SaisieTF.getText().contains("/help"))
            {
                GetHelp();
                return;
            }
            else if(SaisieTF.getText().contains("/question "))
            {

                scan.next();
                BCDigest digest = new BCDigest("MD5");
                String sequence = scan.next();
                String message = scan.next();
                System.out.println("MESSAGE: " + message);
                
                os.write(("POST_QUESTION#" + digest.CreateDigest(message).length + "#").getBytes());
                
                
                os.write(digest.CreateDigest(message));
                
                os.write(("#" + sequence + "#" + Login + "#" + message + "\n").getBytes());
                
                msg = os.toByteArray();
                
            }
            else if(SaisieTF.getText().contains("/repondre "))
            {
                scan.next();
                
                msg = ("ANSWER_QUESTION#" + Login + "#" + scan.next() + "#" + scan.next() + "\n").getBytes();
            }
            else
                msg = ("POST_EVENT#" + Login + "#" + SaisieTF.getText() + "\n").getBytes();
        
        
            DatagramPacket dp = new DatagramPacket(msg, msg.length, addrGroupe, PortChat);
            soc.send(dp);
            
            SaisieTF.setText(null);
            
        } catch (IOException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConversTA;
    private javax.swing.JTextField SaisieTF;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void TraceEvents(String com) {
        ConversTA.append(com.trim() + "\n");
        ConversTA.setForeground(Color.BLACK);
    }
    
    public void GetHelp() {
        ConversTA.append("Server > [[ H E L P ]]\n");
        ConversTA.append("Server > Pour consulter l'aide, tappez: /help.\n");
        ConversTA.append("Server > Pour poser une question, tappez: /question <USER> <MESSAGE>.\n");
        ConversTA.append("Server > Pour répondre à une question, tappez: /repondre <NUMQUESTION> <MESSAGE>.\n");
    }
}
